### PR TITLE
Update items

### PR DESCRIPTION
**Pull request by sparcut**
Updated items, adding new items.

Unminified so you can see no hidden nasties, also kept the old `items.json` naming it `_olditems.json`, so you can compare if you like.

Added encoding and all, might refine item update script and make another PR so you can easily update `items.json` in the future.

### CODE REVIEW

**Comment by atjeff** [comment]
Hey @sparcut, 

Thanks for your interest, contributions to my project. Truly a great feeling when others want to contribute. I'm not sure how I feel about this PR... Obviously I want the items updated (and un-minified for development), however I don't want to un-minify the items json unless we introduce a install script that minifies for production. Thoughts?

Thanks,
Jeff

**Comment by sparcut** [comment]
I wasn't sure about minifying at first, however, since it's not being served over a network I thought it wouldn't matter.

Though whatever you feel is necessary.

**Comment by atjeff** [comment]
Hmm. @sparcut let's remove the old items file and then i'll merge.

Thanks!

**Comment by sparcut** [comment]
@atjeff Requested change made.

**Review by atjeff — APPROVED** [review]

**Pull request merged**
